### PR TITLE
Fix base fee calculation for pre-london fork

### PR DESCRIPTION
**Pull request by sieniven**
## Summary

- More context on the issue: https://github.com/0xPolygonHermez/cdk-erigon/issues/773
- Adds a pre-london fork height check before internally calling CalcBaseFee
- Resolves the issue where transactions below initial base fee protocol parameters will not get rejected from the txpool, but get stuck forever in baseFee subpool

### CODE REVIEW

**Comment by revitteth** [comment]
Block gas limit tests failing.

**Comment by sieniven** [comment]
@revitteth Thanks for the review. Fixed the failing block gas limits test.

**Review by mandrigin — CHANGES_REQUESTED** [review]
Won’t that allow txs with 0 gas fees to be sent to the network?

**Comment by sieniven** [comment]
@mandrigin as discussed, this PR should not let that happen. As the chain is running on pre-london fork anyway and since the design of the txpool is designed for post-london fork, the correct behavior will be for all txs to be promoted to the pending pool from the baseFee pool. However, txs with low gas prices of below initial base fee are able to enter the pool but get stuck in the baseFee pool forever. This bug on the txpool to add a minimum price limit check is resolved in #803.

The correct fixes will be to fork guard the base fee calculation function, and together with the fixes on #803, we should see the desired behavior in the pool while safeguarding against gasless txs.

**Review by mandrigin — APPROVED** [review]

**Pull request merged**
