### PR TITLE
Upstream merge 

### PR DESCRIPTION
**Pull request by anshalshukla**
Includes cancun eips

### CODE REVIEW

**Comment by cffls** [comment]
@cla-bot check

**Comment by cffls** [comment]
Cumulative index stage was removed from upstream. Do we still need it in cdk-erigon?

**Comment by cffls** [comment]
Some smoke tests were performed on a local devnet. 
The devnet uses cdk-erigon as both sequencer and RPC node. Transactions were sent and successfully included in L2 blocks. L2 blocks were successfully verified on L1.

**Comment by battlmonstr** [comment]
Hello. Could you please tweak the cla-bot to not check upstream people? It spams us with mentions (see its comments above).

**Comment by cffls** [comment]
Closing this PR as we are tracking everything in https://github.com/0xPolygonHermez/cdk-erigon/tree/zkevm-2.60

**Pull request closed without merging**
