### PR TITLE
Xiong/opt smt

### PR DESCRIPTION
**Pull request by louisliu2048**
try to optimize `InsertBatch` proess, it sames work, but in fact not:

before opt:
image

after opt:
image

the time spend on `zkIncrementIntermediateHashes` and `postBlockStateHandling` process almost not change. We should have a asnyc process to save smt data to database.

### CODE REVIEW

**Comment by louisliu2048** [comment]
After analyzing the detailed logs, I discovered several specific phenomena:
1. The percentage of time that the calculateAndSaveHashes function takes up in the InsertBatch function is decreasing, indicating that the code changes are effective.
2. The performance of the smt.Db operations has decreased with the modified code, which may be related to the concentration of data writing in the calculateAndSaveHashes function.

**Comment by V-Staykov** [comment]
Opening routines in recursion seems dangerous to me. In some bad cases it can open thousands of routines. Basically 2^n.

It would be better to have queues in routines amounting to the processor count and put in them the synchronized calculation of the hashes. Other than that it is a great idea.

**Comment by louisliu2048** [comment]
> Opening routines in recursion seems dangerous to me. In some bad cases it can open thousands of routines. Basically 2^n.
> 
> It would be better to have queues in routines amounting to the processor count and put in them the synchronized calculation of the hashes. Other than that it is a great idea.

Yes, if we want to use concurrency, we would need to use thread pool. However, based on our current tests, we've found that the performance bottleneck isn't there, but rather in the database's read and write operations. The cdk-erigon hasn't migrated Erigon's asynchronous read/write database feature, which is causing the current database read and write operations to take a significant amount of time.

we are trying to migrate async read/write database feature into our branch.

**Comment by mandrigin** [comment]
@louisliu2048 yeah, but first it would be nice to wait for rebasing to Erigon 2.60.x (latest release), that will happen after the sequencer is nice and stable.

**Comment by louisliu2048** [comment]
> @louisliu2048 yeah, but first it would be nice to wait for rebasing to Erigon 2.60.x (latest release), that will happen after the sequencer is nice and stable.

Yes, we found that in Erigon, most of the optimizations related to database operations are closely tied to MPT (Merkle Patricia Trie) operations, it will be a litter difficulty to directly use them to SMT.

**Comment by mandrigin** [comment]
> > @louisliu2048 yeah, but first it would be nice to wait for rebasing to Erigon 2.60.x (latest release), that will happen after the sequencer is nice and stable.
> 
> Yes, we found that in Erigon, most of the optimizations related to database operations are closely tied to MPT (Merkle Patricia Trie) operations, it will be a litter difficulty to directly use them to SMT.

but is this PR valid or we can close? it looks like it didn't achieve the necessary improvement, so there might be a totally different implementation?

**Comment by louisliu2048** [comment]
yes, we are still working on it.

**Comment by louisliu2048** [comment]
image

After optimizations, the performance improved by approximately 15%

@V-Staykov @mandrigin help to review this pr, please.

**Comment by kstoykov** [comment]
In [this PR](https://github.com/0xPolygonHermez/cdk-erigon/pull/1208) we have optimized the SMT incremental build by leveraging the fact (after testing to proof it) that using a single thread to calculate hashes, as producer, and a single thread to write results to db, as consumer, resulted in best performance optimizations. We achieved ~17.7% improvement. Adding more threads for producers actually reduced the performance.

Please test it against your data and let us know if you think that something else could be also improved.

**Comment by kstoykov** [comment]
We can close this one because of the fact that SMT optimization PR is already merged into zkevm.

**Pull request closed without merging**
