### PR TITLE
feat: add flag for empty block close time

### LINKED ISSUE #1518: [Sequencer] - reinstate different closing times for empty vs blocks with txs
By default the times should be the same, but we should allow config to change the closing time for empty vs blocks with txs. This will avoid wasting prover/L1 costs for empty blocks.

### PR DESCRIPTION
**Pull request by MorettiGeorgiev**
Fixes: #1518

- Add ``zkevm.sequencer-empty-block-seal-time`` flag

### CODE REVIEW

**Review by hexoscott — CHANGES_REQUESTED** [review]
The code is sound and looks great, but I'm unsure on the behaviour.  I have configured a node locally like:
```
zkevm.sequencer-block-seal-time: 3s
zkevm.sequencer-empty-block-seal-time: 10s
zkevm.sequencer-batch-seal-time: 15s
```
So I'd expect the node to produce 1 block at 10s, then another at 5s as the batch ticker has ticked.  But every block is 10s in size so some other batch ticker check might be needed here?

If I send a tx to the sequencer it is also mined in a 10s block and followed by a few 3s blocks with this config:

image

Overall it looks great, but needs a few more tweaks to nail the ideal behaviour.

**Comment by MorettiGeorgiev** [comment]
Hey @hexoscott ,

Here’s how I understand the situation:
- **No transactions to be mined**: The value of ``zkevm.sequencer-empty-block-seal-time`` is used, which results in a 10s block time.
- **Transactions to be mined**: The value of ``zkevm.sequencer-block-seal-time`` is used leading to a 3s block time.

So, what happens is:
	1.	No transactions -> blocks seal every 10s.
	2.	Transactions arrive -> blocks seal faster, every 3s.
	3.	Once those transactions are mined -> block time goes back to 10s.

This explains the alternating block times you’re seeing (10s followed by a few 3s).

Now, this got me thinking:
If the block time is meant to be constant, wouldn’t that already be the behavior *before* the changes?

I might be misunderstanding something here, but yeah, that’s how I see it. Let me know what you think — happy to chat more

**Comment by hexoscott** [comment]
Hi @MorettiGeorgiev,

You're understanding is correct there, but if a TX arrives and we're already over the 3s block time we should close the block immediately.  Then go straight back to 10s blocks if there is nothing in the pool.

The purpose for this flag is to allow slow networks that only receive a handful of transactions an hour to not have high L1 fees.  When the network is quiet we build blocks slowly, when transactions arrive we want to get receipts to them as soon as possible.

In my testing when I sent a TX the block it was mined in was 10s and the following block with no transactions was 3s.  I would have thought to see the tx get mined in a block that was between 3-10s and the following block to be 10s.

**Comment by hexoscott** [comment]
After some back and forth on this one it looks like I was just getting confused by the view from polycli and block times there.  Sequencer logs show the behaviour we expect.

**Review by hexoscott — APPROVED** [review]

**Pull request merged**
