### PR TITLE
Add index to callLog and recalculate the index when a call is reverted

### PR DESCRIPTION
**Pull request by Damantino**
The system did not include the logIndex field in call logs, which is crucial for correctly sorting and referencing events recorded during the execution. The update introduces the ability to assign a unique index to each call log, allowing for precise tracking of the sequence of events. It also ensures that the log indices are appropriately adjusted in case a call is reverted, guaranteeing that the sequence of events remains consistent and easy to follow.

### CODE REVIEW

**Review by mandrigin — APPROVED** [review]

**Comment by revitteth** [comment]
@Damantino please could you comment saying 'I accept the terms of the CLA' and I will summon the CLA bot so we can merge this PR 😄

**Comment by Damantino** [comment]
I accept the terms of the CLA.

Is this enough?

**Comment by revitteth** [comment]
@cla-bot check

**Comment by krlosMata** [comment]
@cla-bot check

**Comment by revitteth** [comment]
@Damantino thanks so much for the contribution!

**Comment by Damantino** [comment]
You are welcome guys! 😁

**Pull request merged**
