### PR TITLE
Verifier fixes

### PR DESCRIPTION
**Pull request by hexoscott**

### CODE REVIEW

**Comment by kstoykov** [comment]
Could someone else try whether tx-repeater works alongside a sequencer compiled from this branch, because it does not work on my local setup. Tx-repeater itself it fine but the sequencer goes into infinite loop because it is unable to verify batches.

P.S. I'm trying to repeat mainnet transactions.

**Comment by hexoscott** [comment]
Looks like this is an issue with the stream itself, I get timeouts locally trying to sync from it.  Will take a look

**Comment by kstoykov** [comment]
> Looks like this is an issue with the stream itself, I get timeouts locally trying to sync from it. Will take a look

I got either "erigon state root mismatch" if a tx is a funding (from our faucet wallet) or "error in response: EXECUTOR_ERROR_DB_KEY_NOT_FOUND" if a tx is a regular repeated mainnet tx.

**Comment by mandrigin** [comment]
@kstoykov what if you disable the upstream executor?

**Comment by mandrigin** [comment]
@hexoscott I drafted that until the known issue with erigon-to-erigon is fixed

**Comment by kstoykov** [comment]
> @kstoykov what if you disable the upstream executor?

Tx-repeater works as expected by disabling the remote executor.

**Comment by hexoscott** [comment]
I think there is a separate task here to make the datastream stage also async like the verifier which will solve the stream problems.  At the moment the stream is only populating when you get block N+1 because we're waiting on verifications.  Going to make this a proper PR now that erigon-to-erigon sync is working again.

**Review by revitteth — APPROVED** [review]

**Pull request merged**
