### PR TITLE
Fix kurtosis and use a stable kurtosis release

### PR DESCRIPTION
**Pull request by cffls**

### CODE REVIEW

**Review by Stefan-Ethernal — DISMISSED** [review]

**Review by revitteth — DISMISSED** [review]

**Review by kstoykov — APPROVED** [review]

**Comment by kstoykov** [comment]
@cffls Latest changes of Kurtosis causes "Monitor verified batches" to take ages.

**Review by kstoykov — CHANGES_REQUESTED** [review]
v0.2.4 cannot pass "Monitor verified batches" step. The last working commit is 7643bbc4b6bfc44e499015ab229fba087bf79d4c

In addition to that the flag "zkevm.sequencer-non-empty-batch-seal-time" must be removed from templates/cdk-erigon/config.yml because it is no longer relevant

**Comment by cffls** [comment]
Thanks @kstoykov . There is probably something wrong with the rpc node. Will look into it.

**Comment by cffls** [comment]
Looks like kurtosis is passing now.

**Review by Stefan-Ethernal — APPROVED** [review]

**Review by kstoykov — APPROVED** [review]

**Pull request merged**
