### PR TITLE
refactor: remove AddressAdmin config

### PR DESCRIPTION
**Pull request by vcastellm**
This PR removes the unused config file parameter AdminAddress as it's not needed. No event is being generated with this address so there's no need to read anything.

The admin address is not a contract address but an EOA that can be mutable.

This is aligned in the config in cdk-erigon with zkevm-node.

### CODE REVIEW

**Comment by Stefan-Ethernal** [comment]
@vcastellm remember to remove providing the `zkevm.address-admin` in the Kurtosis CDK, as the Kurtosis deployment fails with the following error (https://github.com/0xPolygonHermez/cdk-erigon/actions/runs/11027906212/job/30627088896?pr=1220):

```go
failed setting config flags from yaml/toml file: failed setting zkevm.address-admin flag with value=0xE34aaF64b29273B7D567FCFc40544c014EEe9970 error=no such flag -zkevm.address-admin
```

**Comment by hexoscott** [comment]
As we're removing a flag that will likely be in use in every node already running cdk-erigon it would be good to add an entry into the `DeprecatedFlags` map in flags_zkevm.go to notify users that this flag is no longer in use.

**Comment by vcastellm** [comment]
> As we're removing a flag that will likely be in use in every node already running cdk-erigon it would be good to add an entry into the `DeprecatedFlags` map in flags_zkevm.go to notify users that this flag is no longer in use.

Let's deprecate it

**Comment by vcastellm** [comment]
Applied feedback @hexoscott @Stefan-Ethernal now we only output a warning log stating that the variable is deprecated.

**Review by V-Staykov — APPROVED** [review]

**Pull request merged**
