### PR TITLE
Compatible handling of Initial Sequence Batches logs.

### PR DESCRIPTION
**Pull request by zjg555543**
In actual testing, it was found that the logs of InitialSequenceBatches are not necessarily filled with 24 bytes of zeros at the end. For example, in the XLayer mainnet, it is [23 bytes](https://etherscan.io/tx/0x35215d1a6f4ad41bedfbfc481d53b9d508864a6ace025f243264978e1a755f81#eventlog#88).

### CODE REVIEW

**Comment by mandrigin** [comment]
We don’t support old forkids, are you sure it isn’t related to that?

**Comment by zjg555543** [comment]
> We don’t support old forkids, are you sure it isn’t related to that?

Yes, forkID9.  XLayer mainnet use forkidID 9 for the genesis deployment with validium.
Here is the InitialSequenceBatches event data which fills 23 bytes at the end. https://etherscan.io/tx/0x35215d1a6f4ad41bedfbfc481d53b9d508864a6ace025f243264978e1a755f81#eventlog#88

**Comment by mandrigin** [comment]
@hexoscott that one is for you to review

**Comment by hexoscott** [comment]
Looks fine to me, achieves the same thing, maybe this extra byte is some effective gas price which may or may not be there.  Either way, looks fine :)

**Review by mandrigin — APPROVED** [review]

**Pull request merged**
