### PR TITLE
print empty batchl2data and custom batch 0 cases for getBatchByNumber

### LINKED ISSUE #1021: [RPC] zkevm_getBatchByNumber is returning wrong fields for batches 0 and 1
#### System information
Erigon version: `2.0.0-beta16`

Complementing tests for #958, batch 0 is now returned, but batches 0 and 1 are returning the wrong data.
Requesting batches 2 and 3 worked as expected.

The test was executed in a local network with Legacy and Erigon RPCs.

Batch 0 diff
```diff
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "number": "0x0",
        "coinbase": "0x0000000000000000000000000000000000000000",
        "stateRoot": "0x489e44072604e671274ea693d5309e797fb37a3e0d91e5b0f04639c251c05332",
        "globalExitRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "mainnetExitRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "rollupExitRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "localExitRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "accInputHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "timestamp": "0x6617c9cd",
-       "batchL2Data": "0x",
-       "sendSequencesTxHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
-       "verifyBatchTxHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
+       "batchL2Data": "0x0b0000000000000000",
+       "sendSequencesTxHash": "0x701ac022ebc9e6aac4b0ce1eb86684f0ae19b8eec1c882f7819027040651085f",
+       "verifyBatchTxHash": "0xab2e81cb72604f3b95e010a3c883ef82d05a1ccae3203fabc4f755107bd6257e",
        "closed": true,
        "blocks": [
            {
                "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
                "miner": "0x0000000000000000000000000000000000000000",
                "stateRoot": "0x489e44072604e671274ea693d5309e797fb37a3e0d91e5b0f04639c251c05332",
                "transactionsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
                "receiptsRoot": "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
                "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                "difficulty": "0x0",
                "totalDifficulty": "0x0",
                "size": "0x1f9",
                "number": "0x0",
                "gasLimit": "0x0",
                "gasUsed": "0x0",
                "timestamp": "0x6617c9cd",
                "extraData": "0x",
                "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "nonce": "0x0000000000000000",
                "hash": "0x2b9d8bf8b04959ac6f0396ee32093142a669b1f21d169ccb3199666e2a9ce946",
                "transactions": [],
                "uncles": [],
                "globalExitRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "blockInfoRoot": "0x0000000000000000000000000000000000000000000000000000000000000000"
            }
        ],
        "transactions": null
    }
}
```

Batch 1 diff
```diff
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "number": "0x1",
        "coinbase": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
        "stateRoot": "0xf705ae182cb55c36f21426c25e07d98e7d336330eb5cc9bd56586bb0d91caa6c",
-       "batchL2Data": "0xf9010380808401c9c38094fe12abaa190ef0c8638ee0ba9f828bf41368ca0e80b8e4f811bff7000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a40d5f56745a118d0906a34e69aec8c0db1cb8fa000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005ca1ab1e0000000000000000000000000000000000000000000000000000000005ca1ab1e1bff",
-       "globalExitRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
-       "sendSequencesTxHash": "0xe6af6f07197fb7ed5fde6b6975deb04eb6abd0666bacf61584a4fde3c8e4948c",
+       "batchL2Data": "0x0b0000000000000000f9010380808401c9c38094fe12abaa190ef0c8638ee0ba9f828bf41368ca0e80b8e4f811bff7000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a40d5f56745a118d0906a34e69aec8c0db1cb8fa000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005ca1ab1e0000000000000000000000000000000000000000000000000000000005ca1ab1e1bff",
+       "globalExitRoot": "0xad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb5",
+       "sendSequencesTxHash": "0x701ac022ebc9e6aac4b0ce1eb86684f0ae19b8eec1c882f7819027040651085f",
        "mainnetExitRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "rollupExitRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "localExitRoot": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "accInputHash": "0x9e6d7e93a05a95f9014891c466eb5b5b08649bb1ffcec6c30a6b25c14a00ad16",
        "timestamp": "0x6617c9cd",
        "verifyBatchTxHash": "0xab2e81cb72604f3b95e010a3c883ef82d05a1ccae3203fabc4f755107bd6257e",
        "closed": true,
        "blocks": [
            {
-                "chainId": "0x0",
                "parentHash": "0x2b9d8bf8b04959ac6f0396ee32093142a669b1f21d169ccb3199666e2a9ce946",
                "sha3Uncles": "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
                "miner": "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266",
                "stateRoot": "0xf705ae182cb55c36f21426c25e07d98e7d336330eb5cc9bd56586bb0d91caa6c",
                "transactionsRoot": "0x028e8da17a14af697e0f5469c3e7c3248bbac0ed44348dcf19be152cc9c5c14f",
                "receiptsRoot": "0x662fd6ce91beca580097606b73ccbf7670a03a4c117df35cbb5eb76113fa429e",
                "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000200000000000000000000000000002000000400000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                "difficulty": "0x0",
                "totalDifficulty": "0x0",
                "size": "0x317",
                "number": "0x1",
                "gasLimit": "0x4000000000000",
                "gasUsed": "0x18c8c",
                "timestamp": "0x6617c9cd",
                "extraData": "0x",
                "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
                "nonce": "0x0000000000000000",
                "hash": "0xc2119af2474f7c01f34d2da262433d9dcd867665dd1fde5dce6ec2d6c8caf3df",
                "transactions": [
                    "0x7adde93707c0628ec6c516468f8d13f9efaf7f0c7ffeddbbdfbfef9e8c82f48b"
                ],
                "uncles": [],
                "globalExitRoot": "0xad3228b676f7d3cd4284a5443f17f1962b36e491b30a40b2405849e597ba5fb5",
                "blockInfoRoot": "0x13bd0018c835fdc361a8366f362c9d8bebd4667c1dc5714adb05ac7777c57a39"
            }
        ],
        "transactions": [
            {
                "nonce": "0x0",
                "gasPrice": "0x0",
                "gas": "0x1c9c380",
                "to": "0xfe12abaa190ef0c8638ee0ba9f828bf41368ca0e",
                "value": "0x0",
                "input": "0xf811bff7000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a40d5f56745a118d0906a34e69aec8c0db1cb8fa000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000000",
                "v": "0x1b",
                "r": "0x5ca1ab1e0",
                "s": "0x5ca1ab1e",
                "hash": "0x7adde93707c0628ec6c516468f8d13f9efaf7f0c7ffeddbbdfbfef9e8c82f48b",
                "from": "0x273c0c1382b73c161e315ea700ec73ecb0348238",
                "blockHash": "0xc2119af2474f7c01f34d2da262433d9dcd867665dd1fde5dce6ec2d6c8caf3df",
                "blockNumber": "0x1",
                "transactionIndex": "0x0",
                "chainId": "0x0",
                "type": "0x0",
                "receipt": {
                    "cumulativeGasUsed": "0x18c8c",
                    "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000200000000000000000000000000002000000400000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
                    "logs": [
                        {
                            "address": "0xfe12abaa190ef0c8638ee0ba9f828bf41368ca0e",
                            "topics": [
                                "0x7f26b83ff96e1f2b6a682f133852f6798a09c465da95921460cefb3847402498"
                            ],
                            "data": "0x0000000000000000000000000000000000000000000000000000000000000001",
                            "blockNumber": "0x1",
                            "transactionHash": "0x7adde93707c0628ec6c516468f8d13f9efaf7f0c7ffeddbbdfbfef9e8c82f48b",
                            "transactionIndex": "0x0",
                            "blockHash": "0xc2119af2474f7c01f34d2da262433d9dcd867665dd1fde5dce6ec2d6c8caf3df",
                            "logIndex": "0x0",
                            "removed": false
                        }
                    ],
                    "status": "0x1",
                    "transactionHash": "0x7adde93707c0628ec6c516468f8d13f9efaf7f0c7ffeddbbdfbfef9e8c82f48b",
                    "transactionIndex": "0x0",
                    "blockHash": "0xc2119af2474f7c01f34d2da262433d9dcd867665dd1fde5dce6ec2d6c8caf3df",
                    "blockNumber": "0x1",
                    "gasUsed": "0x18c8c",
                    "from": "0x273c0c1382b73c161e315ea700ec73ecb0348238",
                    "to": "0xfe12abaa190ef0c8638ee0ba9f828bf41368ca0e",
                    "contractAddress": null,
                    "type": "0x0",
                    "effectiveGasPrice": "0x0",
                    "transactionL2Hash": "0x6328738246b074c8fc4e33398c325643d36ec4306d74bfd7e50234a3dfac77b0"
                },
                "l2Hash": "0x6328738246b074c8fc4e33398c325643d36ec4306d74bfd7e50234a3dfac77b0"
            }
        ]
    }
}
```

### PR DESCRIPTION
**Pull request by V-Staykov**

### CODE REVIEW

**Review by hexoscott — COMMENTED** [review]
Looks fine, but I'm worried about new things being added around GERs in the batch data.  We've had a lot of fighting with zkevm_getBatchByNumber having exit root problems which are now stable.  I think we'll want to test these changes in some network that has a legacy node syncing from erigon RPC to verify these changes are OK.

**Comment by V-Staykov** [comment]
zkevm_getBatchByNumber is still not matching legacy for a lot of stuff. The GER's are not completely fixed but they were wrong before anyways. We are kind of blocked right now, because on legacy there seems to be some strange behavios around printing GERs on batches where it wasn't changed.

**Comment by hexoscott** [comment]
@revitteth - would be ace if you can weigh in on this one as you're more familiar with the exit root stuff

**Comment by revitteth** [comment]
> @revitteth - would be ace if you can weigh in on this one as you're more familiar with the exit root stuff

Yeah, looks good to me!

**Review by hexoscott — APPROVED** [review]
If Max is happy with the changes the code looks fine to me

**Pull request merged**
