### PR TITLE
chore: lint hermezconfig yaml examples

### PR DESCRIPTION
**Pull request by leovct**
- Removed unnecessary quotes in yaml files.
- Applied linting to ensure proper formatting using the following command:
`yamllint --config-data "{rules: {document-start: false, line-length: {max: 160}}}"`

### CODE REVIEW

**Review by mandrigin — DISMISSED** [review]

**Comment by mandrigin** [comment]
@leovct thanks so much for your contribution! would you mind to accept the CLA so I can merge it?

**Comment by leovct** [comment]
> @leovct thanks so much for your contribution! would you mind to accept the CLA so I can merge it?

Yes sure but I have no idea how to do that... 😅

Do I need to submit a PR to add myself to the [`.clabot`](https://github.com/0xPolygonHermez/clabot-config/blob/master/.clabot) contributors list?

PS: I also realised there was another config file for `x1config`, hence the extra commits!

**Comment by mandrigin** [comment]
@revitteth can you help with CLA?

**Comment by revitteth** [comment]
@leovct please comment stating acceptance of the terms, and we can get your contribution in! 🚀

**Comment by krlosMata** [comment]
@cla-bot check

**Comment by leovct** [comment]
I have read the Individual/Corporate CLA document and accept its terms. Looking forward to contributing!

**Review by mandrigin — APPROVED** [review]

**Comment by mandrigin** [comment]
thanks a lot for your contribution!

**Pull request merged**
