### PR TITLE
feat: :sparkles: add l1syncer to rpcdaemon

### PR DESCRIPTION
**Pull request by Damantino**
Added config and code to add l1Syncer to RPCDaemon. Before this addition the method "zkevm_getBatchByNumber" would fail if requested to the RPCDaemon.

### CODE REVIEW

**Review by revitteth — APPROVED** [review]

**Review by mandrigin — APPROVED** [review]

**Comment by mandrigin** [comment]
@Damantino your commits should be signed and verified by GitHub for this to be merged.

**Comment by Damantino** [comment]
hi @mandrigin 
Is there a way to sign this commit?

**Comment by Damantino** [comment]
@mandrigin I managed to sign it. Is anything else I have to do?

**Comment by revitteth** [comment]
@Damantino please resolve conflicts and we can get this in :)

**Comment by hexoscott** [comment]
We have conflicts here now with zkevm.  Is there any intention on supporting running cdk-erigon as an RPCDaemon process?  To date all testing and verifying has been done running "full fat erigon".

**Comment by Damantino** [comment]
Hey guys, think that with newer updates this makes no sence since getting L1Syncer for the RPCDaemon to work propoerly would need refactor.

**Comment by hexoscott** [comment]
Thanks @Damantino - shall we close the PR then?

**Comment by Damantino** [comment]
Yes, @hexoscott I'll try refactor and open a new one

**Pull request closed without merging**
