### PR TITLE
use plonky2 lib to optimization poseidon hash

### PR DESCRIPTION
**Pull request by louisliu2048**
After testing, we found that the Poseidon hash process accounts for about 20% of the total block execution time in the current version.
We found that without using GPU hardware acceleration, the Plonky2 Poseidon hash algorithm is 2-3 times faster than the Hermez Poseidon hash algorithm, which is what we are currently using. Therefore, we have integrated the Plonky2 hash algorithm with cgo.

Here is the performance compare:
```
BenchmarkCalculateHash_rust-12    	 1166094	      1001 ns/op
BenchmarkCalculateHash_CPP-12    	  377858	      3206 ns/op
```

And here is the Flame Graph:
use Hermez poseidon hash:
image

use Plonky2 poseidon hash:
image

### CODE REVIEW

**Comment by V-Staykov** [comment]
The precompiled `libposeidon_goldilocks.a` will be a problem. We should not have precompiled stuff in here, so it can be built for any OS.

**Comment by louisliu2048** [comment]
> The precompiled `libposeidon_goldilocks.a` will be a problem. We should not have precompiled stuff in here, so it can be built for any OS.

 we have script in Dockerfile to build the target lib for different os

**Comment by kstoykov** [comment]
Let's use pure C implementation. This way we can use CGO and compile it as a part of node compilation process.

**Comment by louisliu2048** [comment]
> Let's use pure C implementation. This way we can use CGO and compile it as a part of node compilation process.

Yes, the other approach is to optimize the C version of the Poseidon hash.

**Pull request closed without merging**
