### PR TITLE
Set DynamicConfigs path to config directory

### PR DESCRIPTION
**Pull request by vcastellm**
Instead of hardcoding dynamic configs path to a directory in user's home path, assume dynamic config files for a given network will be found along the main configuration file.

### CODE REVIEW

**Comment by Sharonbc01** [comment]
Hi @mandrigin I added this PR  R1 RPC on Cardona

**Comment by hexoscott** [comment]
code looks great, I'll give it a whirl when I get the chance and we can get it merged

**Comment by mandrigin** [comment]
@vcastellm please update the respective section in the README, otherwise looks good to me.

**Comment by vcastellm** [comment]
> @vcastellm please update the respective section in the README, otherwise looks good to me.

Done in https://github.com/0xPolygonHermez/cdk-erigon/pull/511/commits/2afcc2a8e6e8ccb550068483c9381b8696075412

**Review by mandrigin — APPROVED** [review]

**Comment by vcastellm** [comment]
FYI @praetoriansentry

**Pull request merged**
