### PR TITLE
This PR introduces allowlist and blocklist functionality to cdk-erigon

### PR DESCRIPTION
**Pull request by rachit77**
This PR introduces three modes—disabled, allowlisted, and blocklisted—into cdk-erigon. It provides the functionality to switch between these modes, with the default mode set to disabled.

In the `disabled` mode, access lists are inactive.
In the `allowlist` mode, only addresses listed in the allow list are permitted to send transactions or deploy contracts, depending on their assigned policy; others are restricted.
In the `blocklist` mode, addresses listed in the block list are restricted from sending transactions or deploying contracts, depending on their assigned policy.
Supported Policies:

`sendTx`: Regulates an account's transaction sending capability.
`deploy`: Manages an account's contract deployment capability.

### CODE REVIEW

**Review by mandrigin — CHANGES_REQUESTED** [review]
Last thing is that go.mod and go.sum changes seems unnecessary here. Can you please clean them up before its ready to be merged?

**Comment by rachit77** [comment]
I accept the terms of the CLA

**Comment by mandrigin** [comment]
@rachit77 quick question — that is an optional tool, right? So I don’t have to use it if I want no blocklists?

**Comment by goran-ethernal** [comment]
> @rachit77 quick question — that is an optional tool, right? So I don’t have to use it if I want no blocklists?

Yes, by default, access lists are disabled, and you do not have to use them.

**Review by mandrigin — APPROVED** [review]
Looks good!

**Comment by mandrigin** [comment]
@goran-ethernal can we do a follow-up PR with something like that? https://github.com/0xPolygonHermez/cdk-erigon/issues/409

**Comment by goran-ethernal** [comment]
> @goran-ethernal can we do a follow-up PR with something like that? #409

Yep, we have that in plan/backlog.

**Pull request merged**
