### PR TITLE
check for contract code ending in an empty push pre fork 10

### PR DESCRIPTION
**Pull request by hexoscott**

### CODE REVIEW

**Review by revitteth — DISMISSED** [review]

**Review by mandrigin — DISMISSED** [review]

**Review by afa7789 — COMMENTED** [review]
shouldn't we be using the push code reference here instead of hardcoded number ?

something like :
`"github.com/ledgerwatch/erigon/core/vm"` with `vm.PUSH1` not sure if this is it tough.

or is it cause it can be any of these ?

image

**Comment by hexoscott** [comment]
Using the variable over a magic number would be nice 👍 I guess it could be any of these push opcodes but the original issue was specifically for a PUSH1 without anything to actually push to the stack after it, like a trailing push.  Probably a good idea to check with Ignasi at Polygon, we might need something more sophisticated to handle the other push opcodes.

**Comment by hexoscott** [comment]
@afa7789 - I've moved to using the reference you suggested and merged in zkevm so we can get passing tests.  I just checked with Ignasi and this only affects PUSH1 so we're good to merge once we have approval and passing CI :)

**Comment by afa7789** [comment]
Thats awesome LOL

**Review by mandrigin — APPROVED** [review]

**Pull request merged**
